
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EnergyCompany.Models
{

using System;
    using System.Collections.Generic;
    
public partial class collector
{

    public int id { get; set; }

    public int id_client { get; set; }

    public decimal day_used { get; set; }

    public decimal night_used { get; set; }



    public virtual client client { get; set; }

}

}
