

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EnergyCompany.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EnergyDBEntities3 : DbContext
{
    public EnergyDBEntities3()
        : base("name=EnergyDBEntities3")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<bill> bills { get; set; }

    public virtual DbSet<client> clients { get; set; }

    public virtual DbSet<collector> collectors { get; set; }

    public virtual DbSet<contract> contracts { get; set; }

    public virtual DbSet<tariff> tariffs { get; set; }

}

}

